import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import axios from 'axios'
import { useEffect, useState } from 'react'
import { GetServerSidePropsContext } from 'next'
import { useUserContext } from '@/contexts/UserContext'

export default function Home() {

  const [authLink, setAuthLink] = useState('')
  const { username, guilds } = useUserContext();

  useEffect(() => {
    // call to our "backend" for the auth link
    axios.get("http://localhost:3001/api/auth").then(data => setAuthLink(data.data.auth_link))
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>

        <Link href={authLink}>
          <button>Discord Login</button>
        </Link>

        <div>
          {username}
        </div>

        <div style={{color: "green"}}>
          {guilds.map((item, index) => <div key={index}>{item}</div>)}
        </div>
        
      </div>
    </>
  )
}
